defaults:
  - _self_
  - logger: wandb_disabled
  # - evals/metrics@evals.metrics
  - evals/auto-interpret@evals.auto_interp
  # - evals/toxicity@evals.toxicity
  - model: dpo_gemma_2b
  # - override hydra/launcher: submitit_slurm
seed: 42
checkpoint_dir: adapter
experiment_name: ${evals}_eval