defaults:
  - _self_
  - logger: wandb_disabled
  # - evals/metrics@evals.metrics
  # - evals/auto-interpret@evals.eval2
  - evals/toxicity@evals.toxicity
  - model: base_llama_3_2_1b
  # - override hydra/launcher: submitit_slurm
seed: 42
checkpoint_dir: adapter
experiment_name: ${evals}_eval