defaults:
  - _self_
  - logger: wandb_disabled
  # - evals/metrics@evals.metrics
  # - evals/causal-auto-interpret@evals.causal_auto_interp
  # - evals/topk-lora-autointerp@evals.topk_lora_autointerp
  # - evals/auto-interpret@evals.auto_interp
  # - evals/toxicity@evals.toxicity
  - evals/instruction_following@evals.instruction_following
  # - model: interp_dpo_gemma_large
  # - model: dpo_512_lg_start_sm_end
  # - model: dpo_512_sm_start_lg_end
  # - model: sft_mlp
  # - model: sft_sparse
  # - model: sft_both
  # - model: dpo_512_2
  # - model: dpo_512_4
  # - model: full_1024_1000steps
  # - model: full_1024
  # - model: dpo_dense_32
  # - model: dpo_dense_16
  # - model: dpo_dense_8
  #- model: dpo_4096
  # - model: dpo_8192_comments
  # - model: dpo_4096_comments
  #- model: dpo_4096_17layer
  # - model: dpo_8192_18layer
  # - model: dpo_4096_18layer
  # - model: dpo_1024_18layer
  # - model: dpo_8192_18layer
  - model: dpo_512_4_18layer
  # - model: dpo_1024
  # - model: interp_dpo_gemma_large_5k
  # - override hydra/launcher: submitit_slurm
seed: 42
checkpoint_dir: adapter
experiment_name: ${evals}_eval

