name: auto-interpret
layer_idx: 13
k: ${model.k}
r: ${model.r}
collect_activations: False
score_activations: True
seq_len: 2048
# n_tokens: 200000
n_tokens: 50000000
batch_size: 5

build_eval_function:
  _target_: src.evals.causal_auto_interp
