name: auto-interpret
layer_idx: 18
k: ${model.k}
r: ${model.r}
collect_activations: False
score_activations: True
seq_len: 1024
# n_tokens: 200000
n_tokens: 2500000000
# n_tokens: 2500000000
batch_size: 1

build_eval_function:
  _target_: src.evals.causal_auto_interp
