method: "sft"

defaults:
  - model: gemma_2_2b
  - experiment/topk_enhanced_sparse@sft_experiment
  - experiment/topk_enhanced_sparse@dpo_experiment
  - dataset/enhanced_multi@sft_dataset
  - dataset/hh-rlhf@dpo_dataset
  - base_sft_merged_model: gemma_2_2b
  - quantization: 4bit

dump_trained_model: True
dump_path: "models/sft_enhanced_sparse/${training.model.model_name}"

sft:
  enabled: True
  packing: False
  completion_only_loss: True  
  max_seq_length: 2048        
  num_epochs: 1               
  batch_size_train: 2
  gradient_accumulation_steps: 4
  gradient_checkpointing: True
  optim: "adamw_torch"
  lr: 3e-5
  warmup_ratio: 0.05
  bf16: True
  fp16: False
  max_grad_norm: 0.5
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 5
  eval_steps: 250 # for testing
  eval_strategy: "steps"
  # max_steps: 50
  max_steps: 7500
  batch_size_eval: 1
  weight_decay: 0.005
  push_to_hub: False
  do_eval: True

dpo:
  enabled: False
