name: "gemma"
version: 2.0
size: "2B"
type: dpo_model
k: 32
r: 4096
base_model: "/home/cvenhoff/lora_interp/experiments/merged/google/gemma-2-2b_sft"
model_it_name: "google/gemma-2-2b-it"
adapter_checkpoint_dir: "/home/cvenhoff/lora_interp/experiments/gemma-2-2b_topk_dpo_r4096_k32_steps5000/final_adapter"
train_steps: 5000